version: "3.8"
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=genealogy
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ../db/mysql:/var/lib/mysql
      - ../initdb/mysql:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local
